version: "3"
services:
  ddnss:
    image: ddnss:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ddnss
    ports:
      - 5000:5000
    volumes:
      - ./data:/ddnss/data
    environment:
      - TZ=Asia/Shanghai
      # - CF_TOKEN=<CLOUDFLARE_TOKEN>
      # - CF_ZONE_ID=<CLOUDFLARE_ZONE_ID>
      # - CF_ZONE_NAME=<CLOUDFLARE_ZONE_NAME>
      # - DDNS_KEY=<KEY>
    restart: always
