version: "3"

services:
  ddnss:
    image: ddnss:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ddnss
    ports:
      - 5000:5000
    volumes:
      - ./data:/ddnss/data
    environment:
      - TZ=Asia/Shanghai
      # - GUNICORN_BIND = "[::]:5000"
      # - GUNICORN_WORKERS = 2
      # - GUNICORN_WORKER_CLASS = "gevent"

      # - CLOUDFLARE_TOKEN = None
      # - CLOUDFLARE_ZONE_ID = None
      # - CLOUDFLARE_ZONE_NAME = None

      # - DDNS_KEY = None
    restart: always
