services:
  ddnss:
    image: ddnss:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ddnss
    ports:
      - 5533:5533
    volumes:
      - ./data:/ddnss/data
    environment:
      - TZ=Asia/Shanghai
      # - CLOUDFLARE_TOKEN = None
      # - CLOUDFLARE_ZONE_ID = None
      # - CLOUDFLARE_ZONE_NAME = None

      # - DDNS_TOKEN = None
    restart: always
