# SQLALCHEMY_ECHO: True
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:123456@127.0.0.1:3306/ddns

CLOUDFLARE:
  TOKEN: your cloudflare token
  ZONE_ID: your zone id
  ZONE_NAME: example.com
